locations:
  convert: /opt/local/bin/convert
  ffmpeg: /opt/local/bin/ffmpeg
  curl: /opt/local/bin/curl
  flickrocket: /bin/echo
  ffprobe: /opt/local/bin/ffprobe
  mogrify: /opt/local/bin/mogrify
  mkisofs: /opt/local/bin/mkisofs
  dvdauthor: /opt/local/bin/dvdauthor
  
codec:
  mp4_decode: h264_vdpau
  mp4_encode: h264_videotoolbox
  mp4_simple: mpeg4
    
  

default:
  assembly: /Users/colin/Documents/Appcelerator_Studio_Workspace/JobCard/Assembly
  finish: /Users/colin/Documents/Appcelerator_Studio_Workspace/JobCard/Finished
  scratch: /Users/colin/Documents/Appcelerator_Studio_Workspace/JobCard/Scratch
  source: /Users/colin/Documents/Appcelerator_Studio_Workspace/JobCard/EdgeSource01
  deliveries: /Users/colin/Documents/Appcelerator_Studio_Workspace/JobCard/


functions:
  capture: CAPTURE
  transcode: TRANSCODE
  video1: makeVideo
  video2: makeVideo
  photoset1: makePhotoSet
  photoset2: makePhotoSet
  photoset3: makePhotoSet
  photoset4: makePhotoSet   
  box_cover: makeBoxCover
  promoimg: makePromoImg
  book: makeBook
  videoinfo: makeVideoInfo

compliance:
  licensedefault: Edge Interactive  
  template: /Users/colin/Documents/Appcelerator_Studio_Workspace/JobCard/example/compliance_template.txt
  preview_color: blue
  preview_font_color: yellow
  preview_font_size: 48
  preview_x: 100
  preview_y: 100
  compliance_color: green
  compliance_font: /Library/Fonts/Arial.ttf
  compliance_text_color: FFFFFF
  # Text Size Based on 1920x1080; automatically scaled
  compliance_text_size: 30

 
clips4sale:
  ftpsite: 192.168.23.128
  edge0001: MyPassword
  edge0002: AnotherPassword
  edge0003: YetAnotherPassword

flickrocket:  
  username: username
  password: password
    
boxcover:
  font: /Library/Fonts/Skia.ttf
  star_size: 150
  support_size: 120
  shorttitle_size: 150
  partno_size: 150
  title_size: 160
  title_location: right 
  font_color: white
  

    