locations:
  convert: /usr/bin/convert
  ffmpeg: /usr/local/bin/ffmpeg
  curl: /usr/bin/curl
  flickrocket: /bin/echo
  ffprobe: /usr/local/bin/ffprobe
  mogrify: /usr/bin/mogrify
  mkisofs: /usr/bin/mkisofs
  dvdauthor: /usr/bin/dvdauthor
  atomicparsley: /usr/bin/AtomicParsley
  
codec:
  mp4_decode: h264_cuvid
  mp4_encode: h264_nvenc
  mp4_simple: mpeg4
  mp4_jpeg: mjpeg
  mp4_accel: '-hwaccel cuvid'
  mp4_threads: '-threads 8'
  mp4_scalefilter: scale_npp

  

default:
  assembly: /edge/Assembly
  finish: /edge/Finished
  scratch: /edge/Scratch
  source: /edge/EdgeSource01
  deliveries: /edge/Deliveries
  templates: /usr/local


compliance:
  licensedefault: Edge Interactive  
  template: /edge/JobCard/templates/compliance_template.txt
  preview_color: DarkMagenta
  preview_font_color: White
  preview_font_size: 48
  preview_x: 100
  preview_y: 100
  preview_suffix: _title
  preview_ext: .mp4
  preview_font: /edge/JobCard/fonts/Arial.ttf
  compliance_color: DarkMagenta
  compliance_font: /edge/JobCard/fonts/Arial.ttf
  compliance_text_color: white
  # Text Size Based on 1920x1080; automatically scaled
  compliance_text_size: 30
  compliance_suffix: _compliance
  compliance_ext: .mp4

 
clips4sale:
  ftpsite: 192.168.23.128
  edge0001: MyPassword
  edge0002: AnotherPassword
  edge0003: YetAnotherPassword

flickrocket:  
  username: username
  password: password
    
boxcover:
  font: /edge/JobCard/fonts/Skia.ttf
  star_size: 150
  support_size: 120
  keyword_size: 150
  partno_size: 150
  title_size: 150
  title_location: right 
  font_color: white
  suffix: _box_cover
  box_width: 3724
  box_height: 5616
  

    