locations:
  convert: /usr/bin/convert
  ffmpeg: /usr/bin/ffmpeg
  curl: /usr/bin/curl
  flickrocket: /bin/echo
  ffprobe: /usr/bin/ffprobe
  mogrify: /usr/bin/mogrify
  mkisofs: /usr/bin/mkisofs
  dvdauthor: /usr/bin/dvdauthor
  
codec:
  mp4_decode: h264_vdpau
  mp4_encode: libx264
  mp4_simple: mpeg4
    
  

default:
  assembly: /mnt/hgfs/JobCard/Assembly
  finish: /mnt/hgfs/JobCard//Finished
  scratch: /mnt/hgfs/JobCard/Scratch
  source: /mnt/hgfs/JobCard/EdgeSource01
  deliveries: /mnt/hgfs/JobCard/Delivery


functions:
  capture: CAPTURE
  transcode: TRANSCODE
  video1: makeVideo
  video2: makeVideo
  photoset1: makePhotoSet
  photoset2: makePhotoSet
  photoset3: makePhotoSet
  photoset4: makePhotoSet   
  box_cover: makeBoxCover
  promoimg: makePromoImg
  book: makeBook
  videoinfo: makeVideoInfo

compliance:
  licensedefault: Edge Interactive  
  template: templates/compliance_template.txt
  preview_color: blue
  preview_font_color: yellow
  preview_font_size: 48
  preview_x: 100
  preview_y: 100
  compliance_color: green
  compliance_font: /home/jobber/jobber/Arial.ttf
  compliance_text_color: FFFFFF
  compliance_text_size: 20

 
clips4sale:
  ftpsite: 192.168.23.128
  edge0001: MyPassword
  edge0002: AnotherPassword
  edge0003: YetAnotherPassword

flickrocket:  
  username: username
  password: password
    
boxcover:
  font: /home/jobber/jobber/Skia.ttf
  star_size: 150
  support_size: 120
  keyword_size: 150
  partno_size: 150
  title_size: 150
  title_location: right 
  font_color: white
  suffix: _box_cover
  box_width: 3724
  box_height: 5616
  

    