locations:
  convert: /usr/bin/convert
  ffmpeg: /usr/local/bin/ffmpeg
  curl: /usr/bin/curl
  flickrocket: /bin/echo
  ffprobe: /usr/bin/ffprobe
  mogrify: /usr/bin/mogrify
  mkisofs: /usr/bin/mkisofs
  dvdauthor: /usr/bin/dvdauthor
  
codec:
  mp4_decode: h264_vda
  mp4_encode: h264_videotoolbox
  mp4_simple: mpeg4
  mp4_jpeg: mjpeg
  mp4_accel: '-hwaccel videotoolbox'
  mp4_threads: '-threads 8'
  

default:
  assembly: /edge/Assembly
  finish: /edge/Finished
  scratch: /edge/Scratch
  source: /edge/EdgeSource01
  deliveries: /edge/Delivery


compliance:
  licensedefault: Edge Interactive  
  template: /usr/local/templates/compliance_template.txt
  preview_color: blue
  preview_font_color: yellow
  preview_font_size: 48
  preview_x: 100
  preview_y: 100
  compliance_color: green
  compliance_font: /usr/local/fonts/Arial.ttf
  compliance_text_color: FFFFFF
  compliance_text_size: 20

 
clips4sale:
  ftpsite: 192.168.23.128
  edge0001: MyPassword
  edge0002: AnotherPassword
  edge0003: YetAnotherPassword

flickrocket:  
  username: username
  password: password
    
boxcover:
  font: /usr/local/fonts/Skia.ttf
  star_size: 150
  support_size: 120
  keyword_size: 150
  partno_size: 150
  title_size: 150
  title_location: right 
  font_color: white
  suffix: _box_cover
  box_width: 3724
  box_height: 5616
  

    